### ISSUE TITLE
Does your database contain 6D pose information?

### ISSUE THREAD

**Issue by NagabhushanSN95** [montefiore-ai/midair-dataset#5]
Hi,
I'm looking for databases that provide frames and depth maps along with 6D pose information and camera intrinsic matrix. From your database pages [this](https://midair.ulg.ac.be/), [this](https://midair.ulg.ac.be/download.html) and [this](https://midair.ulg.ac.be/data_organization.html), I was able to figure out that frames, depth, and position data are available. It is not clear to me if your database also contains the angle/view information. Basically, I'm looking to see if I can construct the transformation matrix (consisting of rotation matrix and translation vector). I can construct the translation vector. But I'm not sure if the relative rotation matrix between the consecutive frames can be constructed. Can you please confirm if this data is available? Also, is the camera intrinsic matrix available?

Thanks

**Comment by michael-fonder** [comment]
Hi,

Sorry for the very long delay... I didn't see your issue previously.

Yes, the dataset provides all the information you need. You can build the transformation matrix giving the pose of the drone (or the camera) by using the position vector and the quaternion orientation given in the groundtruth data (the quaternion can be converted in a rotation matrix).

For full res pictures (1024x1024px), the intrinsic matrix `K`of the camera is given by:
```
    [fx 0  cx]   [512  0  512]
K = [0  fy cy] = [ 0  512 512]
    [0  0  1 ]   [ 0   0   1 ]
```
