### ISSUE TITLE
What's the focal length？

### ISSUE THREAD

**Issue by Wanghy118** [montefiore-ai/midair-dataset#6]
Hi，in your paper, the FOV is set to 90°，what is the focal length?

**Comment by michael-fonder** [comment]
Hi,
The focal length is 512 for full res pictures (1024x1024px). To be complete, the camera intrinsic matrix `K` is the following one:
```
    [fx 0  cx]   [512  0  512]
K = [0  fy cy] = [ 0  512 512]
    [0  0  1 ]   [ 0   0   1 ]
```

**Comment by Wanghy118** [comment]
Thank you!
