### ISSUE TITLE
The altitude ranges?

### ISSUE THREAD

**Issue by Wanghy118** [montefiore-ai/midair-dataset#7]
Could you please provide the altitude ranges of the flight? In your title, it says "  extremely low altitude", but I didn't find any specific data about the altitude. Thank you!!!

**Comment by michael-fonder** [comment]
I cannot given you precise numbers as this piece of information is tricky to get (especially in environments with a lot of relief). Most of the trajectories were recorded with the drone flying lower than the tree canopy. So, it is safe to say than they were recorded at an altitude located between 0 and 10 meters above ground. For the few trajectories recorded above treetops, I would say that the drone never flies higher than 50m above ground.

**Comment by Wanghy118** [comment]
Thanks! Your information is very helpful to me!
